server:
  port: 51804
spring:
  application:
    name: leadnews-search
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
#      username: root
#      password: 123456
      host: 127.0.0.1
      port: 27017
      database: leadnews-history
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  elasticsearch:
    uris: http://localhost:9201
    connection-timeout: 10000
    socket-timeout: 3000
    username: elastic
    password: ${ES_PASSWORD:x8YMlQeWvd4IGPnrb-4k}
elasticsearch:
  article:
    index: ${ES_ARTICLE_INDEX:app_info_article}

